export const statements = [
  { id: '1', statement: 'Klimapolitik muss harte Bretter bohren' },
  { id: '2', statement: 'Sehen Klimaschützer das Glas eher voll als leer' },
  { id: '3', statement: 'Das heißt aber nicht, dass "Bonn" unwichtig wäre, ganz im Gegenteil' },
  { id: '4', statement: 'Die eigentliche Arbeit hat jetzt erst begonnen' },
  { id: '5', statement: 'Muss ein klarer Fahrplant entwickelt werden' },
  { id: '6', statement: 'Bricht eine Lanze für den Klimaschutz' },
  { id: '7', statement: 'Ein Signal für den Klimaschutz' },
  { id: '8', statement: 'Die Zukunft Menschheit steht auf dem Spiel' },
  { id: '9', statement: 'Die Zeit drängt' },
  { id: '10', statement: 'Wenn wir jetzt nicht handeln, ist es zu spät' },
  { id: '11', statement: 'Das Weltklima, das aus den Fugen geraten ist' },
  { id: '12', statement: 'Die Unwetter sind nur ein Vorgeschmack' },
  { id: '13', statement: 'BINGO' },
  { id: '14', statement: 'Die schlimmsten Folgen können wir noch verhindern' },
  { id: '15', statement: 'Unser Klima ist tunsere Zukunft' },
  { id: '16', statement: 'Jetzt muss gehandelt werden' },
  { id: '17', statement: 'Dass zum Verhandeln das Handeln kommt' },
  { id: '18', statement: 'Die Konferenz in Bonn soll die Weichen stellen' },
  { id: '19', statement: 'Dabei steckt der Teufel im Detail' },
  { id: '20', statement: 'Angekommen in den Mühen der Ebene' },
  { id: '21', statement: 'Die Lage ist ernst, aber nicht ohne Hoffnung' },
  { id: '22', statement: 'Dabei steckt der Teufel im Detail' },
  { id: '23', statement: 'Dabei steckt der Teufel im Detail' },
  { id: '24', statement: 'Dabei steckt der Teufel im Detail' },
  { id: '25', statement: 'Dabei steckt der Teufel im Detail' },
]
