export const statements = [
  { id: '1', statement: '1' },
  { id: '2', statement: '2' },
  { id: '3', statement: '3 ' },
  { id: '4', statement: '4' },
  { id: '5', statement: '5' },
  { id: '6', statement: '6' },
  { id: '7', statement: '7' },
  { id: '8', statement: '8' },
  { id: '9', statement: '9' },
  { id: '10', statement: '10' },
  { id: '11', statement: '11' },
  { id: '12', statement: '12' },
  { id: '13', statement: 'BINGO' },
  { id: '14', statement: '14' },
  { id: '15', statement: '15' },
  { id: '16', statement: '16' },
  { id: '17', statement: '17' },
  { id: '18', statement: '18' },
  { id: '19', statement: '19' },
  { id: '20', statement: '20' },
  { id: '21', statement: '21' },
  { id: '22', statement: '22' },
  { id: '23', statement: '23' },
  { id: '24', statement: '24' },
  { id: '25', statement: '25' },
]
